### ISSUE TITLE
sw_file is not defined?

### ISSUE THREAD

**Issue by Lemonsavery** [teleclimber/snowpack-service-worker-assets#1]
https://github.com/teleclimber/snowpack-service-worker-assets/blob/9297b74e0b33ddcacc3dce1f41176bc788ea967c/index.js#L23

Did you forget to define `sw_file`? I'm getting the error `ReferenceError: sw_file is not defined`, and it looks like `sw_file` isn't defined anywhere in your `index.js`.

**Comment by teleclimber** [comment]
Can this be closed too or is this a separate issue from the PR? https://github.com/teleclimber/snowpack-service-worker-assets/pull/2

**Comment by Lemonsavery** [comment]
I believe this is a separate issue. I don't have experience making packages
for npm, but it doesn't look like that mentioned variable gets set anywhere.
